name: Deploy Multidocker
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Build React in Dev & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t dayfa1r/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true dayfa1r/react-test npm test
  
  build:
    name: Build & Push Production Images
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t dayfa1r/multi-client ./client
      - run: docker build -t dayfa1r/multi-nginx ./nginx
      - run: docker build -t dayfa1r/multi-server ./server
      - run: docker build -t dayfa1r/multi-worker ./worker
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker push dayfa1r/multi-client
      - run: docker push dayfa1r/multi-nginx
      - run: docker push dayfa1r/multi-server
      - run: docker push dayfa1r/multi-worker
  
  deploy:
    name: Deploy to AWS Elastic Beanstalk
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        name: Generate Deployment Package
        run: zip -r deploy.zip . -x '*.git*'
      -
        name: Put package in EBS
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-664418971463
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip